import type { LocationSnapshot } from "@/lib/domain/types";

export type NigeriaLocationPoint = LocationSnapshot & {
  lat: number;
  lng: number;
};

export const NIGERIA_LOCATION_POINTS: NigeriaLocationPoint[] = [
  {
    lat: 12.0022,
    lng: 8.5919,
    displayLocality: "Sabon Gari",
    areaBucket: "sabon-gari",
    admin2Name: "Kano Municipal",
    admin2Type: "LGA",
    stateName: "Kano",
    confidenceScore: 0.91,
  },
  {
    lat: 7.4095,
    lng: 3.9096,
    displayLocality: "Bodija",
    areaBucket: "bodija",
    admin2Name: "Ibadan North",
    admin2Type: "LGA",
    stateName: "Oyo",
    confidenceScore: 0.88,
  },
  {
    lat: 4.8156,
    lng: 7.0498,
    displayLocality: "GRA Phase 2",
    areaBucket: "gra-phase-2",
    admin2Name: "Port Harcourt",
    admin2Type: "LGA",
    stateName: "Rivers",
    confidenceScore: 0.89,
  },
  {
    lat: 6.4482,
    lng: 7.5104,
    displayLocality: "New Haven",
    areaBucket: "new-haven",
    admin2Name: "Enugu North",
    admin2Type: "LGA",
    stateName: "Enugu",
    confidenceScore: 0.9,
  },
  {
    lat: 5.1127,
    lng: 7.3737,
    displayLocality: "Ariaria",
    areaBucket: "ariaria",
    admin2Name: "Aba North",
    admin2Type: "LGA",
    stateName: "Abia",
    confidenceScore: 0.87,
  },
  {
    lat: 6.3667,
    lng: 5.6174,
    displayLocality: "Uselu",
    areaBucket: "uselu",
    admin2Name: "Oredo",
    admin2Type: "LGA",
    stateName: "Edo",
    confidenceScore: 0.86,
  },
  {
    lat: 10.486,
    lng: 7.4275,
    displayLocality: "Barnawa",
    areaBucket: "barnawa",
    admin2Name: "Kaduna South",
    admin2Type: "LGA",
    stateName: "Kaduna",
    confidenceScore: 0.91,
  },
  {
    lat: 9.8556,
    lng: 8.8934,
    displayLocality: "Rayfield",
    areaBucket: "rayfield",
    admin2Name: "Jos South",
    admin2Type: "LGA",
    stateName: "Plateau",
    confidenceScore: 0.85,
  },
  {
    lat: 5.0231,
    lng: 7.9469,
    displayLocality: "Ewet Housing",
    areaBucket: "ewet-housing",
    admin2Name: "Uyo",
    admin2Type: "LGA",
    stateName: "Akwa Ibom",
    confidenceScore: 0.92,
  },
  {
    lat: 5.4838,
    lng: 7.0351,
    displayLocality: "Ikenegbu",
    areaBucket: "ikenegbu",
    admin2Name: "Owerri Municipal",
    admin2Type: "LGA",
    stateName: "Imo",
    confidenceScore: 0.87,
  },
  {
    lat: 7.1603,
    lng: 3.3577,
    displayLocality: "Ibara",
    areaBucket: "ibara",
    admin2Name: "Abeokuta South",
    admin2Type: "LGA",
    stateName: "Ogun",
    confidenceScore: 0.88,
  },
  {
    lat: 8.4902,
    lng: 4.5954,
    displayLocality: "Tanke",
    areaBucket: "tanke",
    admin2Name: "Ilorin South",
    admin2Type: "LGA",
    stateName: "Kwara",
    confidenceScore: 0.89,
  },
  {
    lat: 9.0757,
    lng: 7.4911,
    displayLocality: "Wuse 2",
    areaBucket: "wuse-2",
    admin2Name: "Abuja Municipal",
    admin2Type: "Area Council",
    stateName: "FCT",
    confidenceScore: 0.94,
  },
  {
    lat: 6.5152,
    lng: 3.3768,
    displayLocality: "Yaba",
    areaBucket: "yaba",
    admin2Name: "Lagos Mainland",
    admin2Type: "LGA",
    stateName: "Lagos",
    confidenceScore: 0.91,
  },
];
